version: "3.10"

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASSWORD
    networks:
      - "mainnetwork"
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: $MONGO_USERNAME
      ME_CONFIG_MONGODB_ADMINPASSWORD: $MONGO_PASSWORD
      ME_CONFIG_MONGODB_URL: mongodb://$MONGO_USERNAME:$MONGO_PASSWORD@mongo:27017/
    networks:
      - "mainnetwork"

  redis:
    image: redis
    restart: always
    networks:
      - "mainnetwork"

  save_data:
    restart: always
    build: ./save_data
    env_file:
      - .env
    volumes:
      - ./save_data:/app
    networks:
      - "mainnetwork"
    command: [ "python", "db_worker.py" ]


  binance_book:
    restart: always
    depends_on:
      - mongo-express
      - redis
    build: ./binance_book
    volumes:
      - ./binance_book:/app
    ports:
      - "9443:9443"
    networks:
      - "mainnetwork"
    command: [ "python", "main.py" ]

  html:
    restart: always
    build: ./html
    volumes:
      - ./html:/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - "mainnetwork"
    command: ["gunicorn", "-k", "gevent", "-b", "0.0.0.0", "fls:app"]

networks:
  mainnetwork:
    name: "mainnetwork"